blank_issues_enabled: false
contact_links:
  - name: Support us
    url: https://ko-fi.com/tgwolf
    about: Show your support
  - name: Visit our website
    url: https://tgwolf.com/
    about: Visit the TGWolf website and see what else we do and what services we offer
